// Code generated by mockery v2.20.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// freePortProvider is an autogenerated mock type for the freePortProvider type
type freePortProvider struct {
	mock.Mock
}

type freePortProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *freePortProvider) EXPECT() *freePortProvider_Expecter {
	return &freePortProvider_Expecter{mock: &_m.Mock}
}

// getFreePort provides a mock function with given fields:
func (_m *freePortProvider) getFreePort() (uint, error) {
	ret := _m.Called()

	var r0 uint
	var r1 error
	if rf, ok := ret.Get(0).(func() (uint, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() uint); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(uint)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// freePortProvider_getFreePort_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'getFreePort'
type freePortProvider_getFreePort_Call struct {
	*mock.Call
}

// getFreePort is a helper method to define mock.On call
func (_e *freePortProvider_Expecter) getFreePort() *freePortProvider_getFreePort_Call {
	return &freePortProvider_getFreePort_Call{Call: _e.mock.On("getFreePort")}
}

func (_c *freePortProvider_getFreePort_Call) Run(run func()) *freePortProvider_getFreePort_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *freePortProvider_getFreePort_Call) Return(_a0 uint, _a1 error) *freePortProvider_getFreePort_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *freePortProvider_getFreePort_Call) RunAndReturn(run func() (uint, error)) *freePortProvider_getFreePort_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTnewFreePortProvider interface {
	mock.TestingT
	Cleanup(func())
}

// newFreePortProvider creates a new instance of freePortProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newFreePortProvider(t mockConstructorTestingTnewFreePortProvider) *freePortProvider {
	mock := &freePortProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
