// Code generated by mockery v2.20.2. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	v1 "k8s.io/api/core/v1"
)

// podProvider is an autogenerated mock type for the podProvider type
type podProvider struct {
	mock.Mock
}

type podProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *podProvider) EXPECT() *podProvider_Expecter {
	return &podProvider_Expecter{mock: &_m.Mock}
}

// listPods provides a mock function with given fields: _a0, _a1
func (_m *podProvider) listPods(_a0 context.Context, _a1 *portforwarder.listPodsCommand) (*v1.PodList, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *v1.PodList
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *portforwarder.listPodsCommand) (*v1.PodList, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *portforwarder.listPodsCommand) *v1.PodList); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.PodList)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *portforwarder.listPodsCommand) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// podProvider_listPods_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'listPods'
type podProvider_listPods_Call struct {
	*mock.Call
}

// listPods is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *portforwarder.listPodsCommand
func (_e *podProvider_Expecter) listPods(_a0 interface{}, _a1 interface{}) *podProvider_listPods_Call {
	return &podProvider_listPods_Call{Call: _e.mock.On("listPods", _a0, _a1)}
}

func (_c *podProvider_listPods_Call) Run(run func(_a0 context.Context, _a1 *portforwarder.listPodsCommand)) *podProvider_listPods_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*portforwarder.listPodsCommand))
	})
	return _c
}

func (_c *podProvider_listPods_Call) Return(_a0 *v1.PodList, _a1 error) *podProvider_listPods_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *podProvider_listPods_Call) RunAndReturn(run func(context.Context, *portforwarder.listPodsCommand) (*v1.PodList, error)) *podProvider_listPods_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTnewPodProvider interface {
	mock.TestingT
	Cleanup(func())
}

// newPodProvider creates a new instance of podProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newPodProvider(t mockConstructorTestingTnewPodProvider) *podProvider {
	mock := &podProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
